name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25b

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run make
      run: make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        path: |
          libs
          obj/local/*/*.a
        if-no-files-found: error
